# location:	~/.config/kitty/kitty.conf
 font_family		Maple Mono NF CN
 bold_font		auto
 italic_font		auto
 bold_italic_font	auto

 cursor_shape underline

 font_size 10.0

 hide_window_decorations yes

 foregrounf #000000
 background #000000

 background_opacity 1.0
 background_blur 0

 cursor_trail 1
 cursor_trail_decay 0.1 0.2
 cursor_trail_start_threshold 0




include themes/noctalia.conf
