# location:	~/.config/environment.d/value.conf

# EDITOR
EDITOR=nvim
VISUAL=nvim

# softwares and wayland
ELECTRON_OZONE_PLATFORM_HINT=wayland

# Security
BW_SESSION="th41NFt+aslTLDTxNGpm1hByoBlPdKS8RSFJ5MouY3iv9xH/+87+AP1Yd/bWHbZl+GtnHKHYc5r2XaW6GF78Rg=="

