# location:	~/.config/xdg-desktop-portal/portal.conf
[preferred]
default=gtk
org.freedesktop.impl.portal.FileChooser=gtk
# niri need 2 more lines as followed:
# org.freedesktop.impl.portal.ScreenCast=gnome
# org.freedesktop.impl.portal.Screenshot=gnome
